language: objective-c
xcode_project: Clicky.xcodeproj
xcode_scheme: Clicky
xcode_sdk: iphonesimulator7.0
before_install:
  - brew update
  - brew install pyenv
  - eval "$(pyenv init -)"
  - pyenv install 2.7.6
  - pyenv glocal 2.7.6
  - pyenv rehash
  - pip install cpp-coveralls
  - pyenv rehash
before_script:
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/profile/TravisTest.mobileprovision.enc
  -d -a -out scripts/profile/TravisTest.mobileprovision
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/dist.cer.enc -d -a
  -out scripts/certs/dist.cer
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/dist.p12.enc -d -a
  -out scripts/certs/dist.p12
- ./scripts/add-key.sh
after_success:
  - coveralls --exclude lib --exclude tests
env:
  global:
  - APP_NAME="Clicky"
  - DEVELOPER_NAME="iPhone Distribution: Findaway World (LW8G2YK29M)"
  - PROFILE_NAME="TravisTest"
  - secure: csgYi6seWgp5KgEabP0yewCdullpReS7u1hYBlN53jTHHEJHA4/iieXP18Xu+cN2VxhcQvteDQBQN5Po7PWIqe7XFR3/wXvve/5S4d8baOfW5ZhTRrbjMFXYkC9oo9AP7vvj+CsvMW+8UMLTXkimYdu+z6A3QIaPTcVg2cIQi4c=
  - secure: DewJT+XTQDFbxfwpb2vhhq839/CBOuqN+tAtThcZ8BwbA5nh+TaCnYEQXZcPRPQ4Y/9HhRigT93vLjcBI8ebxsF9h4je8OJ8RL8vWAdQg5moK6j5ZVEBdWLdx/0qcBNnrg5VdqqjmoM3Dcd05reaEwWJncTko+pgxavfLKgL36U=
